[tool.poetry]
name = "proseflow"
version = "0.1.0"
description = ""
authors = ["Markus Strasser <strasser.ms@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
nbdev = "^1.1.5"
jupyter = "^1.0.0"
jupyterlab = "^2.2.9"
jupyterlab-git = "^0.23.1"
ipywidgets = "^7.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
