# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_boto_session": "aws_utils.ipynb",
         "write_json_to_s3": "aws_utils.ipynb",
         "write_df_to_s3": "aws_utils.ipynb",
         "read_df_from_s3": "aws_utils.ipynb",
         "read_json_from_s3": "aws_utils.ipynb",
         "load": "load.ipynb",
         "remove_html_tags": "roam_utils.ipynb",
         "remove_buttons": "roam_utils.ipynb",
         "remove_url": "roam_utils.ipynb",
         "remove_attr": "roam_utils.ipynb",
         "replace_block_ref": "roam_utils.ipynb",
         "remove_duplicates": "roam_utils.ipynb",
         "URL_REGEX": "roam_utils.ipynb",
         "clean_sentence": "roam_utils.ipynb",
         "is_too_short": "roam_utils.ipynb",
         "has_stop_symbols": "roam_utils.ipynb",
         "stop_symbols": "roam_utils.ipynb",
         "roam_graph_to_blocks": "roam_utils.ipynb",
         "roam_blocks_to_embeddings_index": "roam_utils.ipynb",
         "gsheet_to_df": "spec.ipynb",
         "TRANSFORMER": "spec.ipynb",
         "SENTENCE_TRANSFORMER": "spec.ipynb",
         "PUBMED_IDS": "spec.ipynb",
         "PUBMED_CONTENT": "spec.ipynb",
         "EMAIL": "spec.ipynb",
         "SPACY_MODEL": "spec.ipynb",
         "STANZA_MODEL": "spec.ipynb",
         "GSHEET": "spec.ipynb",
         "HTML_TAG": "spec.ipynb",
         "URL": "spec.ipynb",
         "SPEC": "spec.ipynb",
         "infer_type": "spec.ipynb",
         "TRANSFORMS": "spec.ipynb",
         "convert": "spec.ipynb",
         "STRING_FUNCS": "text.ipynb",
         "text_to_vector": "text.ipynb",
         "create_index": "text.ipynb",
         "query_index": "text.ipynb",
         "tree_select_kv": "utils.ipynb",
         "deep_path_from_keysequence": "utils.ipynb",
         "get_paths": "utils.ipynb",
         "show_tabs": "utils.ipynb",
         "take_while": "utils.ipynb",
         "partition": "utils.ipynb",
         "partition_all": "utils.ipynb",
         "create_embedding_files_for_visualization": "utils.ipynb",
         "pipe": "utils.ipynb",
         "dedupe_conseq": "utils.ipynb"}

modules = ["aws_utils.py",
           "load.py",
           "roam_utils.py",
           "spec.py",
           "text.py",
           "utils.py"]

doc_url = "https://mkstra.github.io/proseflow/"

git_url = "https://github.com/mkstra/proseflow/tree/master/"

def custom_doc_links(name): return None
