# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load": "load.ipynb",
         "gsheet_to_df": "spec.ipynb",
         "GSHEET": "spec.ipynb",
         "TRANSFORMER": "spec.ipynb",
         "SENTENCE_TRANSFORMER": "spec.ipynb",
         "PUBMED_IDS": "spec.ipynb",
         "PUBMED_CONTENT": "spec.ipynb",
         "EMAIL": "spec.ipynb",
         "SPACY_MODEL": "spec.ipynb",
         "STANZA_MODEL": "spec.ipynb",
         "TRANSFORMS": "spec.ipynb",
         "SPEC": "spec.ipynb",
         "infer_type": "spec.ipynb"}

modules = ["load.py",
           "spec.py"]

doc_url = "https://mkstra.github.io/proseflow/"

git_url = "https://github.com/mkstra/proseflow/tree/master/"

def custom_doc_links(name): return None
